<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerC7lXQxc\App_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerC7lXQxc/App_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerC7lXQxc.legacy');

    return;
}

if (!\class_exists(App_KernelProdContainer::class, false)) {
    \class_alias(\ContainerC7lXQxc\App_KernelProdContainer::class, App_KernelProdContainer::class, false);
}

return new \ContainerC7lXQxc\App_KernelProdContainer([
    'container.build_hash' => 'C7lXQxc',
    'container.build_id' => 'b97ee2c4',
    'container.build_time' => 1772800368,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerC7lXQxc');
