<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerWW2BvJO\App_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerWW2BvJO/App_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerWW2BvJO.legacy');

    return;
}

if (!\class_exists(App_KernelProdContainer::class, false)) {
    \class_alias(\ContainerWW2BvJO\App_KernelProdContainer::class, App_KernelProdContainer::class, false);
}

return new \ContainerWW2BvJO\App_KernelProdContainer([
    'container.build_hash' => 'WW2BvJO',
    'container.build_id' => '3c2582de',
    'container.build_time' => 1749478420,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerWW2BvJO');
