<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerKoI2UJ9\App_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerKoI2UJ9/App_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerKoI2UJ9.legacy');

    return;
}

if (!\class_exists(App_KernelProdContainer::class, false)) {
    \class_alias(\ContainerKoI2UJ9\App_KernelProdContainer::class, App_KernelProdContainer::class, false);
}

return new \ContainerKoI2UJ9\App_KernelProdContainer([
    'container.build_hash' => 'KoI2UJ9',
    'container.build_id' => '61bec915',
    'container.build_time' => 1762530046,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerKoI2UJ9');
