<?php

namespace ContainerC7lXQxc;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRecordTableWidgetDefinitionParserService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\ViewDefinitions\LegacyHandler\Widgets\DefinitionParsers\RecordTableWidgetDefinitionParser' shared autowired service.
     *
     * @return \App\ViewDefinitions\LegacyHandler\Widgets\DefinitionParsers\RecordTableWidgetDefinitionParser
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 3).''.\DIRECTORY_SEPARATOR.'core'.\DIRECTORY_SEPARATOR.'backend'.\DIRECTORY_SEPARATOR.'ViewDefinitions'.\DIRECTORY_SEPARATOR.'LegacyHandler'.\DIRECTORY_SEPARATOR.'Widgets'.\DIRECTORY_SEPARATOR.'WidgetDefinitionParserInterface.php';
        include_once \dirname(__DIR__, 3).''.\DIRECTORY_SEPARATOR.'core'.\DIRECTORY_SEPARATOR.'backend'.\DIRECTORY_SEPARATOR.'Engine'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'DefinitionEntryHandlingTrait.php';
        include_once \dirname(__DIR__, 3).''.\DIRECTORY_SEPARATOR.'core'.\DIRECTORY_SEPARATOR.'backend'.\DIRECTORY_SEPARATOR.'ViewDefinitions'.\DIRECTORY_SEPARATOR.'LegacyHandler'.\DIRECTORY_SEPARATOR.'Widgets'.\DIRECTORY_SEPARATOR.'DefinitionParsers'.\DIRECTORY_SEPARATOR.'RecordTableWidgetDefinitionParser.php';

        return $container->privates['App\\ViewDefinitions\\LegacyHandler\\Widgets\\DefinitionParsers\\RecordTableWidgetDefinitionParser'] = new \App\ViewDefinitions\LegacyHandler\Widgets\DefinitionParsers\RecordTableWidgetDefinitionParser(($container->privates['App\\Engine\\Service\\ActionAvailabilityChecker\\ActionAvailabilityChecker'] ?? $container->load('getActionAvailabilityCheckerService')));
    }
}
